version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: purgecss-webpack-plugin
    versions:
    - 4.0.0
